### Get All Categories
GET http://localhost:3000/api/categories
Accept: application/json
X-API-Key: RAHASIA

### Get detail category
GET http://localhost:3000/api/categories/15
Accept: application/json
X-API-Key: RAHASIA

### Create categories
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json
X-API-Key: RAHASIA

{
  "name": ""
}

### Update categories
PUT http://localhost:3000/api/categories/15
Accept: application/json
Content-Type: application/json
X-API-Key: RAHASIA

{
  "name": "Spy"
}

### Delete categories
DELETE http://localhost:3000/api/categories/13
Accept: application/json
X-API-Key: RAHASIA